import type { Metadata } from "next";
import Landingpage from "../components/landingpage";
import { redirect } from "next/navigation";
export const metadata: Metadata = {
  title: "Landingpage",
  description: "Generated by create next app",
};

const page = () => {
  return redirect("/");
  return (
    <>
      <Landingpage />
    </>
  );
};

export default page;
