name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test --if-present

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::606802968668:role/GitHubOIDCRole
          role-session-name: github-actions
          aws-region: af-south-1
          audience: sts.amazonaws.com

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region af-south-1 --name kitops-eks --role-arn arn:aws:iam::606802968668:role/GitHubOIDCRole 

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region af-south-1 | docker login --username AWS --password-stdin 606802968668.dkr.ecr.af-south-1.amazonaws.com

      - name: Generate Image Tag
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t admin-webapp:${{ env.IMAGE_TAG }} .
        shell: bash

      - name: Tag Docker Image
        run: |
          docker tag admin-webapp:${{ env.IMAGE_TAG }} 606802968668.dkr.ecr.af-south-1.amazonaws.com/admin-webapp:${{ env.IMAGE_TAG }}

      - name: Push Docker Image to ECR
        run: |
          docker push 606802968668.dkr.ecr.af-south-1.amazonaws.com/admin-webapp:${{ env.IMAGE_TAG }}

      - name: Output Image URI
        run: |
          echo "Image pushed to: 606802968668.dkr.ecr.af-south-1.amazonaws.com/admin-webapp:${{ env.IMAGE_TAG }}"

      - name: Update Kubernetes manifests with new image tag
        run: |
          # Using sed to replace the image tag in the Kubernetes manifest
          sed -i "s|admin-webapp:.*|admin-webapp:${{ env.IMAGE_TAG }}|" kubernetes/webapp.yml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "villagesquareltd"
          git config --global user.email "villagesquare130@gmail.com"
          git add kubernetes/webapp.yml
          git commit -m "Updated image tag to ${{ env.IMAGE_TAG }}"
          git push

      - name: Apply Kubernetes deployment
        run: |
          aws eks update-kubeconfig --region af-south-1 --name kitops-eks
          kubectl apply -f kubernetes/webapp.yml --validate=false