name: CI / Build & Publish Docker

# Trigger on push to admin-webapp branch or main branch, or manually
on:
  push:
    branches:
      - admin-webapp
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/admin-webapp

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read        # needed for checkout
      packages: write       # needed to push images to GHCR
      id-token: write       # optional for OIDC

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js (for Next.js build)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run tests (optional, continues if fails)
      - name: Run tests
        run: npm test || echo "No tests or failed, continuing"

      # 5. Build Next.js app
      - name: Build Next.js app
        run: npm run build

      # 6. Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 7. Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 8. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      # 9. Notify post-buil
      - name: Post-build notification
        run: echo "Docker image pushed: ${{ env.IMAGE_NAME }}:${{ github.sha }}"
