name: CI / Build & Publish Docker

on:
  push:
    branches: 
      - admin-webapp   # Trigger on admin-webapp branch
      - main           # Optional: include main branch for production
  workflow_dispatch:   # Manual trigger

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/admin-webapp

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests (optional)
      - name: Run tests
        run: npm test || echo "No tests or failed, continuing"

      # Build Next.js app
      - name: Build Next.js app
        run: npm run build

      # Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with caching
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags:
            - ${{ env.IMAGE_NAME }}:latest
            - ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      # Post-build notification
      - name: Post-deploy notification
        run: echo "Image pushed: ${{ env.IMAGE_NAME }}:${{ github.sha }}"
