name: CI / Build & Publish Docker

on:
  push:
    branches:
      - admin-webapp   # triggers only on admin-webapp branch
  workflow_dispatch:   # allows manual trigger

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/admin-webapp

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests (optional)
      - name: Run tests
        run: |
          if npm run -s test; then
            echo "Tests passed"
          else
            echo "No tests or tests failed but continuing (adjust as needed)"
          fi

      # Build Next.js app
      - name: Build Next.js app
        run: npm run build

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      # Post-deploy notification
      - name: Post-deploy notification
        run: echo "Image pushed: ${{ env.IMAGE_NAME }}:${{ github.sha }}"



